[global_config]
  geometry_hinting = True
  window_state = maximise
  borderless = True
  extra_styling = False
  scroll_tabbar = True
  homogeneous_tabbar = False
  title_hide_sizetext = True
  title_transmit_fg_color = "#f9f06b"
  title_transmit_bg_color = "#000000"
  title_receive_fg_color = "#62a0ea"
  title_receive_bg_color = "#000000"
  title_inactive_fg_color = "#9a9996"
  title_inactive_bg_color = "#000000"
  inactive_color_offset = 1.0
  suppress_multiple_term_dialog = True
  title_use_system_font = False
  title_font = FiraCode Nerd Font Mono weight=453 14
  title_at_bottom = True
[keybindings]
[profiles]
  [[default]]
    background_darkness = 0.9
    background_type = transparent
    cursor_shape = underline
    cursor_fg_color = "#000000"
    cursor_bg_color = "#f9f06b"
    cursor_color_default = False
    font = FiraCode Nerd Font Mono weight=453 14
    foreground_color = "#ffffff"
    scrollbar_position = hidden
    scrollback_lines = 5000000
    exit_action = hold
    use_system_font = False
[layouts]
  # [[default]]
  #   [[[child0]]]
  #     type = Window
  #     parent = ""
  #     order = 0
  #     position = 0:0
  #     maximised = True
  #     fullscreen = False
  #     size = 1920, 1080
  #     title = alexandredelaloy@DLT-LP-53:~
  #     last_active_term = 84c37112-db6d-43f0-8553-773c545fbb67
  #     last_active_window = True
  #   [[[terminal1]]]
  #     type = Terminal
  #     parent = child0
  #     order = 0
  #     profile = default
  #     uuid = 84c37112-db6d-43f0-8553-773c545fbb67
  #     command = ""
  [[default]]
    [[[child0]]]
      type = Window
      parent = ""
      order = 0
      position = 0:0
      maximised = True
      fullscreen = False
      size = 1920, 1080
      title = alexandredelaloy@DLT-LP-53:~/__/ALTEIA
      last_active_term = 9bdf0f98-814b-4d4f-8a78-7a0fa37d0627
      last_active_window = True
    [[[child1]]]
      type = HPaned
      parent = child0
      order = 0
      position = 958
      ratio = 0.5002610966057441
    [[[terminal2]]]
      type = Terminal
      parent = child1
      order = 0
      profile = default
      uuid = 9bdf0f98-814b-4d4f-8a78-7a0fa37d0627
      directory = __/ALTEIA
    [[[child3]]]
      type = VPaned
      parent = child1
      order = 1
      position = 538
      ratio = 0.5004651162790698
    [[[terminal4]]]
      type = Terminal
      parent = child3
      order = 0
      profile = default
      uuid = ceeb2567-7813-417d-bd93-8909e9fbbdeb
      command = htop
    [[[terminal5]]]
      type = Terminal
      parent = child3
      order = 1
      profile = default
      uuid = 4c2e5ab2-9696-4ebc-9f76-49c7b96b14aa
      directory = go/src/github.com/gogolcorp/go-eland
[plugins]
