[global_config]
  geometry_hinting = True
  window_state = maximise
  borderless = True
  extra_styling = False
  scroll_tabbar = True
  homogeneous_tabbar = False
  title_hide_sizetext = True
  title_transmit_fg_color = "#f9f06b"
  title_transmit_bg_color = "#000000"
  title_receive_fg_color = "#62a0ea"
  title_receive_bg_color = "#000000"
  title_inactive_fg_color = "#9a9996"
  title_inactive_bg_color = "#000000"
  inactive_color_offset = 1.0
  suppress_multiple_term_dialog = True
  title_use_system_font = False
  title_font = FiraCode Nerd Font Mono weight=453 12
[keybindings]
[profiles]
  [[default]]
    background_darkness = 0.8
    background_type = transparent
    cursor_shape = underline
    cursor_color = "#ef2929"
    cursor_color_fg = False
    font = FiraCode Nerd Font Mono weight=453 14
    foreground_color = "#ffffff"
    scrollback_lines = 5000000
    use_system_font = False
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
      profile = default
[plugins]
