name: "CD"

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "**/go.*"

jobs:
  CD:
    name: CD
    runs-on: ubuntu-latest
    steps:
      # Checkout to current workspace
      - name: 1 - CHECKOUT
        uses: actions/checkout@v3

        # Login to container registry
      - name: 2 - LOGIN TO GHCR.IO
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Setup variable for Docker tag
      - name: 3 - SETUP ENV VARS
        run: |
          echo "SHA=$(echo $GITHUB_SHA | head -c8)" >> $GITHUB_ENV
          echo "DATE=$(date +%Y%m%d%H%M)"           >> $GITHUB_ENV
          echo "BRANCH=$GITHUB_HEAD_REF"            >> $GITHUB_ENV

        # Build and push the app with given file and tag
      - name: 4 - BUILD + PUSH
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: build/package/go-eland/Dockerfile
          tags: |
            ghcr.io/gogolcorp/go-eland:${{ env.BRANCH }}-${{ env.SHA }}-${{ env.DATE }}
            ghcr.io/gogolcorp/go-eland:${{ env.BRANCH }}-${{ env.SHA }}
            ghcr.io/gogolcorp/go-eland:latest

        # Output the logs
      - name: 5 - IMAGE DIGEST
        run: echo ${{ steps.docker_build.outputs.digest }}
