name: "CI"

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '**/*.go'
      - '**/go.*'


jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      # Checkout to current workspace
    - name: 1 - CHECKOUT
      uses: actions/checkout@v3

      # Install golang with specific version
    - name: 2 - SETUP GO
      uses:  actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: 'go.sum'

      # Cache go modules to make the build faster
    - name: 3 - CACHE GO MODULES
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

      # Lint files before build using gofmt
    - name: 4 - LINT
      run: |
        gofmt -e -l -s -w .
    
      # Build the project 
    - name: 5 - BUILD
      run: |
        go build -v ./...