name: GO RELEASER

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
       # Checkout to current workspace
      - name: 1 - CHECKOUT
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        run: git fetch --force --tags

        # Install golang with specific version
      - name: 2 - SETUP GO
        uses:  actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: 'go.sum'
        
        # Create release using 
      - name: 3 - CREATE RELEASE
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
